service: diff-checker
configValidationMode: error

frameworkVersion: "2"

custom:
  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  environment:
    DIFF_TABLE: "diff-${self:custom.stage}"
    LATEST_REVISION_INDEX: latestRevision
    MIDDLEWARE_API_DOMAIN: https://bk6tatcsyl.execute-api.us-east-1.amazonaws.com/prod
    SECRET_ID: surveillance/SecretKey
    SECRET_KEY: SECRET_KEY
    NUM_URLS_TO_SCAN: 2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "sns:Publish"
          Resource: "arn:aws:sns:us-east-1:*:*"
        - Effect: "Allow"
          Action: "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:*"

functions:
  diffChecker:
    handler: handler.diffCheck
    events:
      - schedule: rate(5 hours)

resources:
  Resources:
    DiffTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DIFF_TABLE}
        AttributeDefinitions:
          - AttributeName: urlId
            AttributeType: S
          - AttributeName: version
            AttributeType: N
          - AttributeName: latest
            AttributeType: S
        KeySchema:
          - AttributeName: urlId
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.LATEST_REVISION_INDEX}
            KeySchema:
              - AttributeName: urlId
                KeyType: HASH
              - AttributeName: latest
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DiffTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource:
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.DIFF_TABLE}
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.DIFF_TABLE}/index/${self:provider.environment.LATEST_REVISION_INDEX}
        Roles:
          - Ref: IamRoleLambdaExecution
