service: friday-demo
configValidationMode: off


frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  hello:
    handler: handler.hello
    events: 
      -sqs:
        arn:
          Fn::GetAtt:
            -surveillanceAlertMsg
            -Arn



resources:
  Resources:
    scannedData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: scannedData
        AttributeDefinitions:
          - AttributeName: listingId
            AttributeType: S
        KeySchema:
          - AttributeName: listingId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    surveillanceAlertMsg:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "surveillanceAlertMsg"
    

    SQSPolicy: 
     Type: AWS::SQS::QueuePolicy
     Properties: 
      Queues: 
      - "https://sqs.us-east-1.amazonaws.com/190089000663/surveillanceAlertMsg"
      PolicyDocument: 
       Statement: 
        - 
          Action: 
            - "SQS:SendMessage" 
            - "SQS:ReceiveMessage"
          Effect: "Allow"
          Resource: "arn:aws:sqs:us-east-1:190089000663:surveillanceAlertMsg"

    DynamoDBIamPolicy: 
      Type: AWS::IAM::Policy
      DependsOn: scannedData
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: arn:aws:dynamodb:*:*:table/scannedData
        Roles:
          - Ref: IamRoleLambdaExecution